#cloud-config

packages: 
  - apache2 
  - php 
  - php-mysql 
  - mysql-client
  - git 
  - awscli

package_update: true
package_upgrade: true




write_files: 
  - path: /run/backend.sh
    owner: root:root
    permissions: "777"
    content: |
                #!/bin/bash -xe
                REGION="${aws_region}"
                 #get the private ip address of the Instance Name=Database
                DB_HOST_IP=$(aws --region $REGION ec2 describe-instances --filters "Name=tag:Server,Values=Database" "Name=instance-state-name,Values=running" --query 'Reservations[0].Instances[0].PrivateIpAddress' | sed 's/"//g') 


                cp -r /tmp/sbtphapp-project-devops/backend/sbtph_api/ /var/www/html/

                if [ "$DB_HOST_IP" -ne "null"]; then
                    sudo sed -i "s/[0-9]\+\(\.[0-9]\+\)\{3\}/$DB_HOST_IP/" /var/www/html/sbtph_api/config/database.php
                    sudo sed -i "s/SBTPHAPP_USER_HERE/${mysql_app_user}/" /var/www/html/sbtph_api/config/database.php
                    sudo sed -i "s/SBTPHAPP_PWED_HERE/${mysql_app_pwd}/" /var/www/html/sbtph_api/config/database.php
                fi

                #change ownership to ubuntu user and apache2 group
                chown -R ubuntu:ubuntu /var/www/html

               
                #update region in update_db_ip.sh
                cp /tmp/sbtphapp-project-devops/backend/startup-service/update_db_ip.sh /home/ubuntu/update_db_ip.sh
                sudo sed -i "s/AWS_REGION_HERE/$REGION/" /home/ubuntu/update_db_ip.sh


                chown -R ubuntu:ubuntu /home/ubuntu/update_db_ip.sh
                chmod +x /home/ubuntu/update_db_ip.sh

                cp /tmp/sbtphapp-project-devops/backend/startup-service/update_db_ip.service /etc/systemd/system/

                sudo systemctl daemon-reload
                sudo systemctl enable update_db_ip.service
                sudo systemctl start update_db_ip.service

                cp /tmp/sbtphapp-project-devops/backend/cron/update_db_ip.crontab /tmp/

                # Install the updated crontab
                crontab /tmp/update_db_ip.crontab

                # Remove the temporary file
                rm /tmp/update_db_ip.crontab

                cd .. 
                sudo rm -rf /tmp/sbtphapp-project-devops

             
runcmd:
 - sudo systemctl enable apache2
 - sudo systemctl start apache2 
 - cd /tmp && git clone -b  lift-and-shift https://github.com/robudexIT/sbtphapp-project-devops.git
 - sudo /run/backend.sh