#cloud-config

packages: 
  - apache2 
  - php 
  - php-mysql 
  - mysql-client
  - git 
  - awscli

package_update: true
package_upgrade: true

write_files: 
  - path: /run/frontend.sh
    owner: root:root
    permissions: "777"
    content: |
               #!/bin/bash -xe
                REGION=${aws_region}
                #get the public ip address of the Instance Name=Backend
                AWS_API_IP=$(aws --region $REGION ec2 describe-instances --filters "Name=tag:Server,Values=Backend" Name=instance-state-name,Values=running --query 'Reservations[0].Instances[0].PublicIpAddress' | sed 's/"//g') 
                

                cp -r /tmp/sbtphapp-project-devops/frontend/sbtph_app/ /var/www/html/
                cp /tmp/sbtphapp-project-devops/frontend/startup-service/update_api_ip.service /etc/systemd/system/
                cp /tmp/sbtphapp-project-devops/frontend/startup-service/update_api_ip.sh /home/ubuntu/
                cp /tmp/sbtphapp-project-devops/frontend/cron/update_api_ip.crontab /tmp/

                if [ "$AWS_API_IP" -ne "null" ]; then
                    find /var/www/html/sbtph_app/js/app* -type f -exec sed -E -i "s/\b([0-9]{1,3}\.){3}[0-9]{1,3}\b/$AWS_API_IP/g" {} +
                fi
                sudo chown -R ubuntu:ubuntu /var/www/html
                
                #this code will deal on SPA application 
                mv /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf-backup
                cp  /tmp/sbtphapp-project-devops/frontend/conf/apache2/000-default.conf /etc/apache2/sites-available/
                sudo a2enmod rewrite
                sudo systemctl restart apache2


                sudo sed -i "s/AWS_REGION_HERE/${AWS::Region}/" /home/ubuntu/update_api_ip.sh
                sudo chmod +x /home/ubuntu/update_api_ip.sh
                sudo chown -R ubuntu:ubuntu /home/ubuntu/update_api_ip.sh

                sudo systemctl daemon-reload
                sudo systemctl enable update_api_ip.service
                sudo systemctl start update_api_ip.service

                # Install the updated crontab
                crontab /tmp/update_api_ip.crontab

                # Remove the temporary file
                rm /tmp/update_api_ip.crontab


                cd ..
                sudo rm -rf  /tmp/sbtphapp-project-devops



       
             
runcmd:
 - sudo systemctl enable apache2
 - sudo systemctl start apache2 
 - cd /tmp && git clone -b  lift-and-shift https://github.com/robudexIT/sbtphapp-project-devops.git
 - sudo /run/frontend.sh